name: example
description: customizable calender picker
version: 1.0.0
homepage: https://github.com/gwanhwikim/custom_calender_picker

publish_to: none

environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  custom_calender_picker:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
