name: custom_calender_picker
description: This package is a customizable calender_picker.
version: 0.1.1
homepage: https://github.com/gwanhwikim/custom_calender_picker

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
